spring:
  config:
    import: classpath:application-defaults.yml
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/liquitest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    openfeign:
      client:
        config:
          calculator:
            url: http://localhost:9000/calculator
  kafka:
    bootstrap-servers: localhost:9092
