logging:
  level:
    ru.neostudy.creditbank.dossier: DEBUG
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <example@gmail.com>
    password: <application_password>
    properties:
      mail.smtp:
          auth: true
          starttls.enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
  cloud:
    openfeign:
      client:
        config:
          deal:
            url: http://deal:9001/deal
  kafka:
    bootstrap-servers: broker:9092
  application:
    name: Dossier
server:
  port: 9003


