spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kirilaz0201@gmail.com
    password: oywxujdodnjhmqyd
    properties:
      mail.smtp:
          auth: true
          starttls.enable: true
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: Dossier
server:
  port: 9003

